-- Create ai_whatsapp_nodepath table for AI WhatsApp conversations
CREATE TABLE IF NOT EXISTS ai_whatsapp_nodepath (
    id_prospect INT(11) NOT NULL AUTO_INCREMENT,
    flow_reference VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Reference to chatbot flow being executed',
    execution_id VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Unique execution identifier',
    date_order DATETIME DEFAULT NULL,
    id_device VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    niche VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    prospect_name VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    prospect_num VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    intro VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    stage VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    conv_last TEXT COLLATE utf8mb4_unicode_ci,
    conv_current TEXT COLLATE utf8mb4_unicode_ci,
    execution_status ENUM('active','completed','failed') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flow execution status',
    flow_id VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ID of the current chatbot flow being executed',
    current_node_id VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Current node ID in the chatbot flow',
    last_node_id VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Previous node ID for flow tracking',
    waiting_for_reply TINYINT(1) DEFAULT 0 COMMENT '1 = waiting for user reply, 0 = not waiting',
    balas VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    human INT(11) DEFAULT 0,
    keywordiklan VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    marketer VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_today DATETIME DEFAULT NULL,
    
    PRIMARY KEY (id_prospect),
    UNIQUE KEY uniq_execution_id (execution_id),
    KEY idx_flow_id (flow_id),
    KEY idx_current_node_id (current_node_id),
    KEY idx_id_device (id_device),
    KEY idx_prospect_num (prospect_num)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
