CREATE TABLE IF NOT EXISTS `wasapBot_nodepath` (
  `id_prospect`       INT(11) NOT NULL AUTO_INCREMENT,
  `flow_reference`    VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL,
  `execution_id`      VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL,
  `execution_status`  ENUM('active','completed','failed') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flow execution status',
  `flow_id`           VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'ID of the current chatbot flow being executed',
  `current_node_id`   VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Current node ID in the chatbot flow',
  `last_node_id`      VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Previous node ID for flow tracking',
  `waiting_for_reply` TINYINT(1) DEFAULT 0 COMMENT '1 = waiting for user reply, 0 = not waiting',
  `marketer_id`       VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `prospect_num`      VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `niche`             VARCHAR(300) COLLATE latin1_swedish_ci DEFAULT NULL,
  `instance`          VARCHAR(255) COLLATE latin1_swedish_ci DEFAULT NULL,
  `peringkat_sekolah` VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `alamat`            VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `nama`              VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `pakej`             VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `no_fon`            VARCHAR(20)  COLLATE latin1_swedish_ci DEFAULT NULL,
  `cara_bayaran`      VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `tarikh_gaji`       VARCHAR(20)  COLLATE latin1_swedish_ci DEFAULT NULL,
  `stage`             VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `temp_stage`        VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `conv_start`        VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `conv_last`         TEXT         COLLATE latin1_swedish_ci,
  `date_start`        VARCHAR(50)  COLLATE latin1_swedish_ci DEFAULT NULL,
  `date_last`         VARCHAR(50)  COLLATE latin1_swedish_ci DEFAULT NULL,
  `status`            VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT 'Prospek',
  `staff_cls`         VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `umur`              VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `kerja`             VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `sijil`             VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `user_input`        TEXT         COLLATE latin1_swedish_ci,
  `alasan`            VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  `nota`              VARCHAR(200) COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`id_prospect`),
  INDEX idx_prospect_num (prospect_num),
  INDEX idx_flow_id (flow_id),
  INDEX idx_execution_id (execution_id),
  INDEX idx_instance (instance)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
