// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmsrnunjakejlcvgbfyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptc3JudW5qYWtlamxjdmdiZnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjI2NjUsImV4cCI6MjA2OTMzODY2NX0.HklZQ817Z2gzNmHIX_9yR1jRqYH3JfCvvj24trpvSlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});